### ISSUE TITLE
CodeMadeClock does not run on Windows 10 Pro

### ISSUE THREAD

**Issue by AET4016** [LBognanni/CodeMadeClock#12]
I have installed and run CodeMadeClock successfully on a number of Windows 10 Home computers (and the skin customisation facility is great - thank you!). Today I installed it on a Win10 Pro PC but it would not execute, saying it was incompatible with that version of Windows.

**Comment by LBognanni** [comment]
That's weird @AET4016, is it perhaps being blocked by a your company? 
It would be helpful if you could reply with the exact error message you're getting!

**Comment by AET4016** [comment]
Hello Loris - the computer is used privately by a relative, with no Group Policies applied AFAIK. The message given was just that - 'this program is not compatible...' or words to that effect. Unfortunately I will not be able to replicate the circumstances (long story)

**Comment by LBognanni** [comment]
@AET4016 could it be that the computer was running Windows S instead of Pro? 🤔

**Comment by AET4016** [comment]
No - Windows 10 Pro is what it reported under Settings > About

**Comment by LBognanni** [comment]
@AET4016 I think I know why: It might be an older version of Windows that is not supported - CodeMadeClock targets [a minimum version of windows 10 build 17763](https://github.com/LBognanni/CodeMadeClock/blob/master/src/CodeMade.Clock/CodeMade.Clock.csproj#L3C29-L3C48), which [dates back to August 2021](https://support.microsoft.com/en-us/topic/august-10-2021-kb5005030-os-build-17763-2114-cec503ed-cc09-4641-bdc1-988153e0bd9a)

I'll update the documentation about this, but a simple Windows Update should solve this!

**Comment by AET4016** [comment]
Thank you! If I get the opportunity (unlikely for a while) to check the computer I'll verify the Windows build. However, I would be surprised if it is such an old build, as I thought that updates were being applied...

**Comment by LBognanni** [comment]
I updated the FAQ [on the website](https://codemade.net/clock/), feel free to reopen this if you get the opportunity to check that computer and it was actually on a newer version of windows!
