### ISSUE TITLE
Adjust Font Size to 7 to Fix Overflow in Digital Clock Display

### ISSUE THREAD

**Issue by HanChangHun** [LBognanni/CodeMadeClock#14]
https://github.com/LBognanni/CodeMadeClock/blob/db89d328de2a8c340a360bb09985f673a92732d6/clocks/digital.json#L76

There appears to be an issue with the current digital clock display where the numbers seem to overflow and appear cut off. After analyzing the configuration, it seems that adjusting the font size to 7 would resolve the issue.

**Current Configuration:**
```
"FontSize": 10
```

**Suggested Change:**
```
"FontSize": 7
```

By making this adjustment, the display should render correctly without any overflow. This change will ensure that the numbers fit within the designated area properly.

**Comment by LBognanni** [comment]
Hi @HanChangHun , thanks for reporting this!

It should now be fixed in version ~1.3.14~ [1.3.15](https://github.com/LBognanni/CodeMadeClock/releases/tag/v1.3.15.0). 
Please give it a spin, and feel free to reopen this issue if you still have problems 🙂
