### ISSUE TITLE
To make the clock be at the top of all applications at all times

### ISSUE THREAD

**Issue by ishan-parihar** [LBognanni/CodeMadeClock#9]
Please add an option to make the clock be at the top of all applications at all times.
It is much needed productivity feature.
Thank you

**Comment by LBognanni** [comment]
Hey @ishan-parihar, this should already be the case, is it not for you?
Are there some specific application that stay on top of the clock?

**Comment by ishan-parihar** [comment]
It is not on the top of any applications by default. I am on windows 11
22H2.

I am using a workaround of Powertoys Always on Top to make it work.


[image: Mailtrack]
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
Sender
notified by
Mailtrack
<https://mailtrack.io?utm_source=gmail&utm_medium=signature&utm_campaign=signaturevirality11&>
12/06/23,
05:18:14 PM

**Comment by LBognanni** [comment]
Hi @ishan-parihar, thanks for reporting this bug!

This should now be fixed starting with [version 1.3.10](https://github.com/LBognanni/CodeMadeClock/releases/tag/v1.3.10.0)

Please give it a try, and feel free to reopen this if it's still not working for you
